/**
 * Source of the gate Worker deployed in front of static assets when a Workers deploy is private.
 * Same contract as the tunnel gate: `#key=` in the link → POST /api/session → HttpOnly cookie.
 * The key lives in the CLOUDFACT_KEY secret; optional expiry in the CLOUDFACT_KEY_EXPIRES var.
 * Fails closed: without a key configured, every request gets 503.
 */
import { GATE_HTML } from '../tunnel/gate.js';

export const WORKER_SOURCE = `// generated by cloudfact — gate worker
const COOKIE = 'cloudfact_access';
const GATE_HTML = ${JSON.stringify(GATE_HTML)};
const enc = new TextEncoder();
function timingEqual(a, b) {
  const x = enc.encode(a), y = enc.encode(b);
  if (x.byteLength !== y.byteLength) return false;
  return crypto.subtle.timingSafeEqual(x, y);
}
function cookieValue(request) {
  for (const part of (request.headers.get('cookie') || '').split(';')) {
    const [k, ...v] = part.trim().split('=');
    if (k === COOKIE) return v.join('=');
  }
  return null;
}
const reply = (status, body, headers) =>
  new Response(body, { status, headers: { 'cache-control': 'no-store', 'x-robots-tag': 'noindex, nofollow', ...headers } });

export default {
  async fetch(request, env) {
    const key = env.CLOUDFACT_KEY;
    if (!key) return reply(503, 'cloudfact: key not configured', { 'content-type': 'text/plain' });
    const expired = env.CLOUDFACT_KEY_EXPIRES ? Date.parse(env.CLOUDFACT_KEY_EXPIRES) <= Date.now() : false;
    const url = new URL(request.url);
    if (url.pathname === '/api/session' && request.method === 'POST') {
      const ip = request.headers.get('cf-connecting-ip') || 'unknown';
      if (env.SESSION_LIMIT) {
        try {
          const { success } = await env.SESSION_LIMIT.limit({ key: ip });
          if (!success) return reply(429, '{"error":"rate_limited"}', { 'content-type': 'application/json', 'retry-after': '60' });
        } catch {}
      }
      const auth = request.headers.get('authorization') || '';
      const token = auth.startsWith('Bearer ') ? auth.slice(7) : '';
      if (expired) return reply(401, '{"error":"expired"}', { 'content-type': 'application/json' });
      if (!timingEqual(token, key)) return reply(401, '{"error":"invalid"}', { 'content-type': 'application/json' });
      return reply(204, null, { 'set-cookie': COOKIE + '=' + key + '; Path=/; HttpOnly; Secure; SameSite=Lax' });
    }
    const value = cookieValue(request);
    const ok = !expired && value !== null && timingEqual(value, key);
    if (!ok) return reply(200, GATE_HTML, { 'content-type': 'text/html; charset=utf-8' });
    const res = await env.ASSETS.fetch(request);
    const out = new Response(res.body, res);
    out.headers.set('cache-control', 'private, no-cache');
    out.headers.set('x-robots-tag', 'noindex, nofollow');
    return out;
  },
};
`;

export function wranglerConfig(name: string, compatibilityDate: string): string {
  return JSON.stringify(
    {
      name,
      main: 'index.js',
      compatibility_date: compatibilityDate,
      workers_dev: true,
      preview_urls: false,
      assets: { directory: '../site', binding: 'ASSETS', run_worker_first: true },
      ratelimits: [{ name: 'SESSION_LIMIT', namespace_id: '1001', simple: { limit: 10, period: 60 } }],
    },
    null,
    2,
  );
}
