/**
 * Source of the Worker that fronts an `expose` deploy with Cloudflare Access.
 * The app keeps running on this machine behind a quick tunnel; this Worker gives it a fixed
 * *.workers.dev URL, checks the Cloudflare Access JWT (same code as the asset gate) and, only then,
 * forwards the request to the tunnel, adding the tunnel's own key cookie. Fails closed: without the
 * Access AUD/team configured, or without an origin, every request gets 503.
 */
import { ACCESS_JS } from './access-js.js';

export const PROXY_WORKER_SOURCE = `// generated by cloudfact — access proxy worker
${ACCESS_JS}
const ORIGIN_COOKIE = 'cloudfact_access';
const HOP_BY_HOP = ['connection', 'keep-alive', 'transfer-encoding', 'te', 'trailer', 'proxy-authorization', 'proxy-authenticate'];

export default {
  async fetch(request, env) {
    if (env.CLOUDFACT_ACCESS !== '1' || !env.CLOUDFACT_ACCESS_AUD || !env.CLOUDFACT_ACCESS_TEAM) {
      return reply(503, 'cloudfact: Cloudflare Access is not configured for this app yet', { 'content-type': 'text/plain' });
    }
    let ok = false;
    try {
      ok = await verifyAccess(request, env.CLOUDFACT_ACCESS_TEAM, env.CLOUDFACT_ACCESS_AUD);
    } catch {
      ok = false;
    }
    if (!ok) {
      return reply(
        403,
        'cloudfact: this app is protected by Cloudflare Access and the request carried no valid Access token for it. Sign in at https://' +
          new URL(request.url).host +
          '/ (if you just signed in, the Access application may still be propagating; retry in a minute).',
        { 'content-type': 'text/plain' },
      );
    }
    if (!env.CLOUDFACT_ORIGIN) {
      return reply(503, 'cloudfact: the machine serving this app has no tunnel right now; it should reconnect on its own', {
        'content-type': 'text/plain',
      });
    }
    const url = new URL(request.url);
    const target = new URL(url.pathname + url.search, env.CLOUDFACT_ORIGIN);
    const headers = new Headers(request.headers);
    for (const h of HOP_BY_HOP) headers.delete(h);
    headers.delete('cf-access-jwt-assertion');
    headers.delete('cookie');
    if (env.CLOUDFACT_ORIGIN_KEY) headers.set('cookie', ORIGIN_COOKIE + '=' + env.CLOUDFACT_ORIGIN_KEY);
    headers.set('x-forwarded-host', url.host);
    headers.set('x-forwarded-proto', 'https');
    const init = { method: request.method, headers, redirect: 'manual' };
    if (request.method !== 'GET' && request.method !== 'HEAD') init.body = request.body;
    let res;
    try {
      res = await fetch(target.toString(), init);
    } catch (e) {
      return reply(502, 'cloudfact: the machine serving this app did not answer (' + e + ')', { 'content-type': 'text/plain' });
    }
    if (res.webSocket) return new Response(null, { status: 101, webSocket: res.webSocket });
    const out = new Response(res.body, res);
    out.headers.set('cache-control', 'private, no-cache');
    out.headers.set('x-robots-tag', 'noindex, nofollow');
    return out;
  },
};
`;

/** Worker config for the proxy: no static assets, just the Worker. */
export function proxyWranglerConfig(name: string, compatibilityDate: string): string {
  return JSON.stringify({ name, main: 'index.js', compatibility_date: compatibilityDate, workers_dev: true, preview_urls: false }, null, 2);
}
